import { type NextPage } from "next";
import { useForm } from "react-hook-form";
import Head from "next/head";

const Upload: NextPage = () => {
  const { register, handleSubmit } = useForm();

  const onSubmit = async (data) => {
    const formData = new FormData();

    for (const file of data.file) {
      if (file instanceof File) {
        formData.append("files[]", file);
      }
    }

    const res = await fetch("/api/upload", {
      method: "POST",

      body: formData,
    }).then((res) => {
      const reader = res.body.getReader();

      return res.json();
    });
    alert(JSON.stringify(`${res.message}, status: ${res.status}`));
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <form onSubmit={handleSubmit(onSubmit)}>
          <input type="file" {...register("file")} multiple={true} />

          <input type="submit" />
        </form>
      </main>
    </>
  );
};

export default Upload;
